// svelte/example.svelte
<script>
    let count = 0;

    function increment() {
        count += 1;
    }

    function reset() {
        count = 0;
    }
</script>

<div class="container">
    <h2>The count is {count}</h2>

    <button on:click={increment}> Increment </button>

    <button on:click={reset} disabled={count === 0}> Reset </button>
</div>

<style>
    .container {
        text-align: center;
        padding: 1rem;
        border: 1px solid #ddd;
        border-radius: 8px;
    }

    button {
        background: #ff3e00;
        color: white;
        border: none;
        padding: 0.5rem 1rem;
        border-radius: 4px;
        cursor: pointer;
    }

    button:disabled {
        background: #ccc;
        cursor: not-allowed;
    }
</style>

// lit/example.js
import { LitElement, html, css } from "lit";

class MyCounter extends LitElement {
  static styles = css`
    :host {
      display: block;
      padding: 16px;
      max-width: 200px;
      text-align: center;
      border: 1px solid #ddd;
      border-radius: 8px;
      font-family: sans-serif;
    }
    .count {
      font-size: 2rem;
      margin: 10px 0;
      color: #3b82f6;
    }
    button {
      padding: 8px 16px;
      cursor: pointer;
      background-color: #3b82f6;
      color: white;
      border: none;
      border-radius: 4px;
    }
    button:hover {
      background-color: #2563eb;
    }
  `;

  static properties = {
    count: { type: Number },
  };

  constructor() {
    super();
    this.count = 0;
  }

  _increment() {
    this.count += 1;
  }

  render() {
    return html`
      <div>The Current Count:</div>
      <div class="count">${this.count}</div>
      <button @click="${this._increment}">Increment</button>
    `;
  }
}

customElements.define("x-counter", MyCounter);
